### ISSUE TITLE
new adapter compatibility

### ISSUE THREAD

**Issue by rrrst** [avataranedotas/FluenceZESpy#17]
Could be usefull add compatibility with other ELM version (1.4b, 2.0, 2.1, 2.2 and 2.3)

**Comment by avataranedotas** [comment]
The software is no longer in development. Feel free to use any code.

**Comment by rrrst** [comment]
I'm not familiar with compiling Android apps, but if someone could recompile this app with the string on line 455 of BTELMAsuncTask.java in the following way it would include all subsequent ELMs:

if ((resposta.toLowerCase().contains("v1.4".toLowerCase())) ||(resposta.toLowerCase().contains("v2.0".toLowerCase())) || (resposta.toLowerCase ().contains("v2.1".toLowerCase())) || (resposta.toLowerCase().contains("v2.2".toLowerCase())) || (resposta.toLowerCase().contains(" v2.3".toLowerCase())) ) contagem++;

 

Thanks

**Comment by avataranedotas** [comment]
Please be aware that I had tested (about 10 years ago) newer versions of ELM with Fluence ZE and they **did not work**.

**Comment by rrrst** [comment]
I have some of the last 2.3 (original,  buyed from ELM before it close) and a Fluence in the workshop. If you can recomplile I can test
